### ISSUE TITLE
Trouble on Android

### ISSUE THREAD

**Issue by IceandFire04** [fieryhenry/tbcml#16]
Tried putting in this script:
from tbcml.core import (
    CountryCode,
    GameVersion,
    Apk,
    GamePacks,
    Mod,
    ModEdit,
    CatFormType,
    Cat,
    CatForm,
)

cc = CountryCode.EN

gv = GameVersion.from_string("12.3.0")

apk = Apk(gv, cc)
apk.download()
apk.extract()

apk.download_server_files()
apk.copy_server_files()

game_packs = GamePacks.from_apk(apk)

mod_id = Mod.create_mod_id()

mod = Mod(
    name="Test Mod",
    author="Test Author",
    description="Test Description",
    mod_id=mod_id,
    mod_version="1.0.0",
    password="test",
)

cat_id = 0
cat_form_type = CatFormType.FIRST

form = CatForm(cat_id, cat_form_type, name="Test Cat")

cat = Cat(cat_id)

cat.set_form(cat_form_type, form)

mod_edit = ModEdit(["cats", cat_id], cat.to_dict())

mod.add_mod_edit(mod_edit)

apk.load_mods([mod], game_packs)

print(apk.get_final_apk_path())

and ended with this in Termux:
Traceback (most recent call last):
  File "/storage/emulated/0/download/bcml/script.py", line 1, in <module>
    from tbcml.core import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/tbcml/__init__.py", line 1, in <module>
    from tbcml import core
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/tbcml/core/__init__.py", line 111, in <module>
    from .io.bc_csv import CSV, Delimeter, to_str
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/tbcml/core/io/__init__.py", line 1, in <module>
    from tbcml.core.io import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/tbcml/core/io/bc_image.py", line 4, in <module>
    from PyQt5.QtGui import QImage, QIcon, QPixmap
ModuleNotFoundError: No module named 'PyQt5'

**Comment by fieryhenry** [comment]
Can you try installing from source: https://github.com/fieryhenry/tbcml#from-source, and if that doesn't work try using the `new-structure` branch: https://github.com/fieryhenry/tbcml/tree/new-structure#from-source-recommended

**Comment by MrNooberDude** [comment]
Will do!

**Comment by MrNooberDude** [comment]
Got the apk downloaded this time! This is what it output though:
``Traceback (most recent call last):                                            File "/storage/emulated/0/download/bcml/script.py", line 26, in <module>                                    apk.copy_server_files()                              ^^^^^^^^^^^^^^^^^^^^^                            AttributeError: 'Apk' object has no attribute 'copy_server_files'``

**Comment by fieryhenry** [comment]
sorry, i forgot to update the readme when i removed that function. You should just be able to delete that line from the script `apk.copy_server_files()`

**Comment by MrNooberDude** [comment]
So the script seems to be fine now, but it can't sign the APK I think
``Failed to pack APK: I: Using Apktool 2.9.1
I: Checking whether resources has changed...
I: Building resources...
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_91658046131707131065907225576027859682.tmp, compile, --dir, /data/data/com.termux/files/home/Documents/tbcml/APKs/12.3.0en/extracted/res, --legacy, -o, /data/data/com.termux/files/home/Documents/tbcml/APKs/12.3.0en/extracted/build/resources.zip]
W: /data/data/com.termux/files/usr/tmp/brut_util_Jar_91658046131707131065907225576027859682.tmp[235]: syntax error: unexpected '('

Traceback (most recent call last):
  File "/storage/emulated/0/download/bcml/script.py", line 63, in <module>
    apk.load_mods([mod], game_packs)
  File "/storage/emulated/0/download/bcml/tbcml/src/tbcml/core/io/apk.py", line 1345, in load_mods
    self.load_packs_into_game(game_packs)
  File "/storage/emulated/0/download/bcml/tbcml/src/tbcml/core/io/apk.py", line 373, in load_packs_into_game
    self.sign()
  File "/storage/emulated/0/download/bcml/tbcml/src/tbcml/core/io/apk.py", line 270, in sign
    self.zip_align()
  File "/storage/emulated/0/download/bcml/tbcml/src/tbcml/core/io/apk.py", line 314, in zip_align
    apk_path.copy(self.final_apk_path)
  File "/storage/emulated/0/download/bcml/tbcml/src/tbcml/core/io/path.py", line 198, in copy
    raise FileNotFoundError(f"File not found: {self.path}")
FileNotFoundError: File not found: /data/data/com.termux/files/home/Documents/tbcml/APKs/12.3.0en/jp.co.ponos.battlecatsen-modded-aligned.apk``

Also renamed issue so it's more accurate

**Comment by fieryhenry** [comment]
seems like maybe the architecture you are using isn't supported by apktool unfortunately: https://github.com/iBotPeaches/Apktool/issues/2407 and https://github.com/iBotPeaches/Apktool/issues/3498. I don't know if there is a way to fix it, i'll have to modify the library to use something other than apktool when apktool doesn't work

**Comment by MrNooberDude** [comment]
Maybe I could try overriding the downloaded one with of a different architecture. Would I just delete the `apk.download_server_files()` line and put it in the directory they usually are in?

**Comment by fieryhenry** [comment]
it's the architecture of your device that's the problem, not the architecture of the apk

**Comment by MrNooberDude** [comment]
Oooohhh, okay.

**Comment by IceandFire04** [comment]
Okay, so it's been a while since I looked here and I'm just closing this because it seems like it was fixed
